---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-gateway-fabric
  namespace: nginx-gateway
spec:
  template:
    spec:
      containers:
        - name: nginx
          volumeMounts:
            - mountPath: /etc/nginx/nginx.conf
              name: nginx-conf-override
              subPath: nginx.conf
      volumes:
        - name: nginx-conf-override
          configMap:
            name: nginx-conf-override
