---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: vault-uqhy
spec:
  capacity:
    storage: 7Gi
  accessModes: [ReadWriteOnce]
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /opt/vault/
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: vault-storage
              operator: In
              values: [enabled]
