---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ovndb-backup
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 1Gi
  storageClassName: general
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: ovn-snapshot-cron
spec:
  schedule: 0 0 * * *
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 5
      template:
        spec:
          serviceAccount: ovn
          serviceAccountName: ovn
          restartPolicy: Never
          volumes:
            - name: backup
              persistentVolumeClaim:
                claimName: ovndb-backup
            - name: backup-script
              configMap:
                name: ovn-backup-script
                defaultMode: 0744
          containers:
            - name: ovn-central-backup
              envFrom:
                - configMapRef:
                    name: ovn-backup-config
                - secretRef:
                    name: ovn-backup-swift-tempauth-account
              command: [/backup-script/ovn-backup.sh]
              image: docker.io/kubeovn/kube-ovn:v1.13.13
              imagePullPolicy: IfNotPresent
              volumeMounts:
                - name: backup
                  mountPath: /backup
                - name: backup-script
                  mountPath: /backup-script
